// mapGeo.test.mjs — the data-driven map refactor, held to pixel equivalence.
//
// Run:  node --test .claude/skills/video-factory/engine/*.test.mjs
// (from the repo root — dep() falls through to backend/node_modules)
//
// COMPARISON METHOD. The four shipped variants were rendered through the
// retired hardcoded mapSvg() at three progress values each, and the sha256 of
// every PNG recorded below. The data-driven path must reproduce those pixels
// exactly. Render determinism was verified first (two baseline runs,
// identical hashes), so a hash match IS pixel identity, not luck.
//
// These hashes are tied to the satori/resvg versions in backend/node_modules.
// A dependency bump that changes rasterisation will fail this suite — that is
// a feature (it catches silent render drift), but after eyeballing the new
// output the fixtures are regenerated by running the renders and pasting the
// new hashes here, in the same commit as the bump.

import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, mkdtempSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { renderCard } from "./render.mjs";
import { GEO, geoSvg, validateGeo } from "./mapGeo.mjs";

const TMP = mkdtempSync(path.join(os.tmpdir(), "mapgeo-"));
const sha = (f) => createHash("sha256").update(readFileSync(f)).digest("hex").slice(0, 16);
const render = async (spec, name, p) => {
  const f = path.join(TMP, `${name}.png`);
  await renderCard(spec, f, p);
  return sha(f);
};

// Recorded from the hardcoded mapSvg() at commit 241b5e7 (pre-refactor HEAD).
const BASELINE = {
  "hormuz@0.25": "1df8db92d5568b47", "hormuz@0.6": "a08f090e1d7f1a84", "hormuz@1": "3e35d60625219482",
  "drc@0.25": "e32a7b498d3e081a", "drc@0.6": "91ece37ebca04bd0", "drc@1": "2c3fee324096e967",
  "saudi@0.25": "b2a54279696aa91c", "saudi@0.6": "fe453bdd3167aacb", "saudi@1": "0f46916db389ce27",
  "uae@0.25": "8e39566795a566f4", "uae@0.6": "7c535e7ae7c3ee21", "uae@1": "3d4d4f60a9e4cf78",
};

test("every shipped variant is pixel-identical to the hardcoded original", async () => {
  for (const v of Object.keys(GEO)) {
    for (const p of [0.25, 0.6, 1.0]) {
      const key = `${v}@${p === 1 ? "1" : p}`;
      const got = await render(
        { card: "map", variant: v, kicker: "BASELINE", title: "Equivalence fixture" },
        key, p,
      );
      assert.equal(got, BASELINE[key], `${key}: pixels drifted from the hardcoded original`);
    }
  }
});

// ── The point of the refactor: a NOVEL geography, no engine edit ────────────
// A schematic Bab el-Mandeb — a geography no shipped variant covers — built
// purely from the element grammar. If this renders, a new story's map is an
// authored data blob, not an engine change.
const BAB_EL_MANDEB = {
  defs: [{ id: "wn", from: "#12222c", to: "#0a1319" }, { id: "ln", from: "#1d1811", to: "#12100c" }],
  bg: "url(#wn)",
  elements: [
    { el: "path", d: "M0,0 H700 C640,120 600,260 620,420 L560,700 H0 Z", fill: "url(#ln)", stroke: "landEdge", sw: 3 },
    { el: "path", d: "M1600,0 H860 C900,160 920,300 880,440 L960,700 H1600 Z", fill: "url(#ln)", stroke: "landEdge", sw: 3 },
    { el: "drawPath", d: "M300,650 C480,560 640,500 740,430 C800,388 820,300 860,180", len: 900,
      color: "lime", width: 6, opacity: 0.95, anim: [0.10, 0.55] },
    { el: "pulseMarker", x: 750, y: 430, anim: [0.55, 0.95] },
    { el: "dot", x: 300, y: 650, r: 14, color: "lime", anim: [0.06, 0.24] },
  ],
  labels: [
    { t: "AFRICA", x: 140, y: 200, s: 34, c: "sub", a: [0.02, 0.20] },
    { t: "ARABIAN PENINSULA", x: 1080, y: 180, s: 30, c: "sub", a: [0.06, 0.24], w: 520 },
    { t: "RED SEA", x: 950, y: 560, s: 30, c: "dim", a: [0.10, 0.30] },
    { t: "BAB EL-MANDEB", x: 460, y: 300, s: 44, c: "lime", a: [0.55, 0.90], f: "Anton", w: 620, pinnable: true },
  ],
};

test("a novel geography renders from inline data with no engine edit", async () => {
  const a = await render({ card: "map", geo: BAB_EL_MANDEB, title: "A strait the engine has never seen" }, "novel-1", 1.0);
  const b = await render({ card: "map", geo: BAB_EL_MANDEB, title: "A strait the engine has never seen" }, "novel-2", 0.3);
  assert.notEqual(a, b, "the novel map must animate — identical frames at p=0.3 and p=1 mean it is static");
  // And the pin override reaches the pinnable label.
  const c = await render({ card: "map", geo: BAB_EL_MANDEB, pin: "26 KM WIDE" }, "novel-pin", 1.0);
  assert.notEqual(a, c, "pin text must change the rendered frame");
});

test("an unknown variant with no geo fails loudly, naming the registry", async () => {
  await assert.rejects(
    () => renderCard({ card: "map", variant: "atlantis" }, path.join(TMP, "x.png"), 1),
    /unknown variant "atlantis".*hormuz/s,
  );
});

// ── Validator: reject, never repair ─────────────────────────────────────────

test("validateGeo names the offending element and field", () => {
  assert.deepEqual(validateGeo(GEO.hormuz), [], "shipped data must validate clean");
  const errs = validateGeo({
    bg: "#000",
    elements: [
      { el: "teleport", x: 1, y: 2 },                  // unknown kind
      { el: "drawPath", color: "lime" },               // no len, no d/line
      { el: "dot", x: 5 },                             // missing y
      { el: "pulseMarker", x: 1, y: 2, anim: [0.5] },  // malformed anim
    ],
    labels: [{ t: "X", x: 0, y: 0 }],                  // missing s, c, a
  });
  assert.match(errs.join("\n"), /elements\[0\].*teleport/);
  assert.match(errs.join("\n"), /elements\[1\].*len/);
  assert.match(errs.join("\n"), /elements\[1\].*"d" or "line"/);
  assert.match(errs.join("\n"), /elements\[2\].*"y"/);
  assert.match(errs.join("\n"), /elements\[3\].*anim/);
  assert.match(errs.join("\n"), /labels\[0\]/);
});

test("geoSvg refuses an invalid spec instead of drawing part of it", () => {
  assert.throws(
    () => geoSvg({ bg: "#000", elements: [{ el: "dot", x: 5 }] }, 1, {}),
    /invalid geo spec/,
  );
});
