// mapGeo.test.mjs — the data-driven map refactor, held to pixel equivalence.
//
// Run:  node --test .claude/skills/video-factory/engine/*.test.mjs
// (from the repo root — dep() falls through to backend/node_modules)
//
// COMPARISON METHOD. The four shipped variants were rendered through the
// retired hardcoded mapSvg() at three progress values each, and the sha256 of
// every PNG recorded below. The data-driven path must reproduce those pixels
// exactly. Render determinism was verified first (two baseline runs,
// identical hashes), so a hash match IS pixel identity, not luck.
//
// These hashes are tied to the satori/resvg versions in backend/node_modules.
// A dependency bump that changes rasterisation will fail this suite — that is
// a feature (it catches silent render drift), but after eyeballing the new
// output the fixtures are regenerated by running the renders and pasting the
// new hashes here, in the same commit as the bump.

import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync, mkdtempSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { renderCard } from "./render.mjs";
import { GEO, geoSvg, validateGeo } from "./mapGeo.mjs";

const TMP = mkdtempSync(path.join(os.tmpdir(), "mapgeo-"));
const sha = (f) => createHash("sha256").update(readFileSync(f)).digest("hex").slice(0, 16);
const render = async (spec, name, p) => {
  const f = path.join(TMP, `${name}.png`);
  await renderCard(spec, f, p);
  return sha(f);
};

// Originally recorded from the hardcoded mapSvg() at commit 241b5e7.
//
// RE-RECORDED 2026-09-03 for the contrast-floor palette lift. The equivalence
// this suite exists to prove is DATA-DRIVEN == HARDCODED, and a palette change
// moves both sides identically — so the property survives; only the constants
// it is expressed in moved. Verified the way the header asks rather than by
// eyeballing: each of the twelve renders was compared before and after by ink
// mask (the set of non-ground pixels), and overlap was 100.000% on all twelve.
// The map geometry is bit-identical; the rule and label colours are not.
const BASELINE = {
  "hormuz@0.25": "19f7513b5212d669", "hormuz@0.6": "e4fc9852a3541feb", "hormuz@1": "4459d7eb364b8813",
  "drc@0.25": "c1e7d5a03151e914", "drc@0.6": "b35a0a4b1761b433", "drc@1": "e08f5e98b9d65f9f",
  "saudi@0.25": "6c94e31afd9d3d44", "saudi@0.6": "d43675bcabd32e24", "saudi@1": "ef3713c8c3327783",
  "uae@0.25": "7b50c04f7b47f285", "uae@0.6": "c37bd847764ac990", "uae@1": "e9a01d13632a6f72",
};

test("every shipped variant is pixel-identical to the hardcoded original", async () => {
  for (const v of Object.keys(GEO)) {
    for (const p of [0.25, 0.6, 1.0]) {
      const key = `${v}@${p === 1 ? "1" : p}`;
      const got = await render(
        { card: "map", variant: v, kicker: "BASELINE", title: "Equivalence fixture" },
        key, p,
      );
      assert.equal(got, BASELINE[key], `${key}: pixels drifted from the hardcoded original`);
    }
  }
});

// ── The point of the refactor: a NOVEL geography, no engine edit ────────────
// A schematic Bab el-Mandeb — a geography no shipped variant covers — built
// purely from the element grammar. If this renders, a new story's map is an
// authored data blob, not an engine change.
const BAB_EL_MANDEB = {
  defs: [{ id: "wn", from: "#12222c", to: "#0a1319" }, { id: "ln", from: "#1d1811", to: "#12100c" }],
  bg: "url(#wn)",
  elements: [
    { el: "path", d: "M0,0 H700 C640,120 600,260 620,420 L560,700 H0 Z", fill: "url(#ln)", stroke: "landEdge", sw: 3 },
    { el: "path", d: "M1600,0 H860 C900,160 920,300 880,440 L960,700 H1600 Z", fill: "url(#ln)", stroke: "landEdge", sw: 3 },
    { el: "drawPath", d: "M300,650 C480,560 640,500 740,430 C800,388 820,300 860,180", len: 900,
      color: "lime", width: 6, opacity: 0.95, anim: [0.10, 0.55] },
    { el: "pulseMarker", x: 750, y: 430, anim: [0.55, 0.95] },
    { el: "dot", x: 300, y: 650, r: 14, color: "lime", anim: [0.06, 0.24] },
  ],
  labels: [
    { t: "AFRICA", x: 140, y: 200, s: 34, c: "sub", a: [0.02, 0.20] },
    { t: "ARABIAN PENINSULA", x: 1080, y: 180, s: 30, c: "sub", a: [0.06, 0.24], w: 520 },
    { t: "RED SEA", x: 950, y: 560, s: 30, c: "dim", a: [0.10, 0.30] },
    { t: "BAB EL-MANDEB", x: 460, y: 300, s: 44, c: "lime", a: [0.55, 0.90], f: "Anton", w: 620, pinnable: true },
  ],
};

test("a novel geography renders from inline data with no engine edit", async () => {
  const a = await render({ card: "map", geo: BAB_EL_MANDEB, title: "A strait the engine has never seen" }, "novel-1", 1.0);
  const b = await render({ card: "map", geo: BAB_EL_MANDEB, title: "A strait the engine has never seen" }, "novel-2", 0.3);
  assert.notEqual(a, b, "the novel map must animate — identical frames at p=0.3 and p=1 mean it is static");
  // And the pin override reaches the pinnable label.
  const c = await render({ card: "map", geo: BAB_EL_MANDEB, pin: "26 KM WIDE" }, "novel-pin", 1.0);
  assert.notEqual(a, c, "pin text must change the rendered frame");
});

test("an unknown variant with no geo fails loudly, naming the registry", async () => {
  await assert.rejects(
    () => renderCard({ card: "map", variant: "atlantis" }, path.join(TMP, "x.png"), 1),
    /unknown variant "atlantis".*hormuz/s,
  );
});

// ── Validator: reject, never repair ─────────────────────────────────────────

test("validateGeo names the offending element and field", () => {
  assert.deepEqual(validateGeo(GEO.hormuz), [], "shipped data must validate clean");
  const errs = validateGeo({
    bg: "#000",
    elements: [
      { el: "teleport", x: 1, y: 2 },                  // unknown kind
      { el: "drawPath", color: "lime" },               // no len, no d/line
      { el: "dot", x: 5 },                             // missing y
      { el: "pulseMarker", x: 1, y: 2, anim: [0.5] },  // malformed anim
    ],
    labels: [{ t: "X", x: 0, y: 0 }],                  // missing s, c, a
  });
  assert.match(errs.join("\n"), /elements\[0\].*teleport/);
  assert.match(errs.join("\n"), /elements\[1\].*len/);
  assert.match(errs.join("\n"), /elements\[1\].*"d" or "line"/);
  assert.match(errs.join("\n"), /elements\[2\].*"y"/);
  assert.match(errs.join("\n"), /elements\[3\].*anim/);
  assert.match(errs.join("\n"), /labels\[0\]/);
});

test("geoSvg refuses an invalid spec instead of drawing part of it", () => {
  assert.throws(
    () => geoSvg({ bg: "#000", elements: [{ el: "dot", x: 5 }] }, 1, {}),
    /invalid geo spec/,
  );
});

test("validateGeo requires every field geoSvg dereferences — no undefined attrs", () => {
  const errs = validateGeo({ bg: "#000", elements: [
    { el: "path", d: "M0,0 L1,1", stroke: "landEdge" },                    // no fill
    { el: "regionFill", clip: { d: "M0,0 L1,1" }, color: "alertDim" },     // no clip.id, no x
    { el: "line", a: [0, 0], b: [1, 1] },                                  // no color
  ] });
  assert.match(errs.join("\n"), /elements\[0\].*"fill"/);
  assert.match(errs.join("\n"), /elements\[1\].*"x"/);
  assert.match(errs.join("\n"), /elements\[1\].*clip needs "id"/);
  assert.match(errs.join("\n"), /elements\[2\].*"color"/);
  // And the point of it: valid shipped data still renders zero "undefined".
  const svg = geoSvg(GEO.drc, 0.5, { landEdge: "#2c261d", alert: "#e0452b", alertDim: "#6b1f14", lime: "#dde706" });
  assert.equal((svg.match(/undefined/g) || []).length, 0);
});

test("the pipeline card's map background renders through the geo registry", async () => {
  // THE MISSED CALL SITE. The map refactor converted the map card but left
  // pipeline's background calling the deleted mapSvg — a ReferenceError on
  // any beat using the documented `map` option. This test is the coverage
  // that was absent.
  const spec = { card: "pipeline", kicker: "ROUTE", title: "Around the strait",
    stages: [{ name: "LOAD" }, { name: "PIPE" }, { name: "SHIP" }], map: "saudi" };
  const withMap = await render(spec, "pipeline-map", 0.8);
  const without = await render({ ...spec, map: undefined }, "pipeline-nomap", 0.8);
  assert.notEqual(withMap, without, "the map background must actually draw");
  await assert.rejects(
    () => renderCard({ ...spec, map: "atlantis" }, path.join(TMP, "p.png"), 0.8),
    /pipeline: unknown map variant "atlantis".*hormuz/s,
  );
});
